### ISSUE TITLE
Pingdat fails from OSError on startup

### ISSUE THREAD

**Issue by lemrouch** [jheddings/pingdat#211]
Hi,
I have pingdat as service starting on boot.
Despite having dependency on network-online systemd target it's possible to get error:
```
loaded AppConfig from: /usr/local/pingdat/pingdat.yaml
Starting metrics server -- X.Y.48.1:9056
Exception in thread A.B.24.20-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/pingdat/lib/python3.11/site-packages/pingdat/__init__.py", line 143, in ping_loop
    self.run_ping_test()
  File "/usr/local/pingdat/lib/python3.11/site-packages/pingdat/__init__.py", line 175, in run_ping_test
    resp = self(seq)
           ^^^^^^^^^
  File "/usr/local/pingdat/lib/python3.11/site-packages/pingdat/__init__.py", line 104, in __call__
    return ping(
           ^^^^^
  File "/usr/local/pingdat/lib/python3.11/site-packages/ping3/__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^             
  File "/usr/local/pingdat/lib/python3.11/site-packages/ping3/__init__.py", line 310, in ping
    send_one_ping(sock=sock, dest_addr=dest_addr, icmp_id=icmp_id, seq=seq, size=size)
  File "/usr/local/pingdat/lib/python3.11/site-packages/ping3/__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^             
  File "/usr/local/pingdat/lib/python3.11/site-packages/ping3/__init__.py", line 176, in send_one_ping
    sock.sendto(packet, (dest_addr, 0))  # addr = (ip, port). Port is 0 respectively the OS default behavior will be used. 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 101] Network is unreachable
```
which pingdat is unable to recover from and I have to restart it manually.

**Comment by jheddings** [comment]
Thanks for the bug report!  I've opened #214 that should fix this...

It looks like the low-level `OSError` isn't handled directly by `ping3` so I have added custom error handling.  If you are able to verify that this solves your problem using the branch, that would be helpful!

**Comment by lemrouch** [comment]
Thanks!
New packages are ready on servers but it will take some time to test during reboot as I have to wait for next maintenance window.

**Comment by jheddings** [comment]
From my testing you might see errors on startup, but it will recover with this fix.

```
May 21 22:18:31 raspidev python3[467]: Starting metrics server -- 0.0.0.0:9056
May 21 22:18:31 raspidev python3[467]: PING -- CloudFlare Primary DNS @ 1.1.1.1
May 21 22:18:31 raspidev python3[467]: PING -- Google Primary DNS @ 8.8.8.8
May 21 22:18:31 raspidev python3[467]: network error: CloudFlare Primary DNS => [Errno 101] Network is unreachable
May 21 22:18:31 raspidev python3[467]: network error: Google Primary DNS => [Errno 101] Network is unreachable
May 21 22:18:31 raspidev python3[467]: network error: CloudFlare Primary DNS => [Errno 101] Network is unreachable
May 21 22:18:31 raspidev python3[467]: network error: Google Primary DNS => [Errno 101] Network is unreachable
May 21 22:18:31 raspidev python3[467]: network error: CloudFlare Primary DNS => [Errno 101] Network is unreachable
May 21 22:18:31 raspidev python3[467]: network error: Google Primary DNS => [Errno 101] Network is unreachable
May 21 22:19:48 raspidev python3[467]: PING -- Google Primary DNS @ 8.8.8.8
May 21 22:19:48 raspidev python3[467]: PING -- CloudFlare Primary DNS @ 1.1.1.1
May 21 22:20:48 raspidev python3[467]: PING -- Google Primary DNS @ 8.8.8.8
May 21 22:20:48 raspidev python3[467]: PING -- CloudFlare Primary DNS @ 1.1.1.1
```

I'll go ahead and publish this fix, but please reopen this ticket if you see additional issues!
